[workspace]
members = ["core", "cli"]
default-members = ["cli"]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
cliclack = "0.3"
directories = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
